"""Journal style registry for DocuMentor."""

from __future__ import annotations


STYLE_REGISTRY = {
    "ieee": {
        "style": "IEEE",
        "font": "Times New Roman",
        "body_size_pt": 10,
        "abstract_size_pt": 9,
        "columns": 2,
        "column_gap_inches": 0.25,
        "margin_inches": 0.75,
        "page_size": "letter",
        "body_alignment": "justified",
        "line_spacing": 1.0,
        "paragraph_spacing_after_twips": 80,
        "first_line_indent_inches": 0.0,
        "reference_hanging_indent_inches": 0.25,
        "section_rules": {
            "numbering": "roman",
            "heading_style": "small_caps_centered",
            "subsection_numbering": "alpha",
            "subsection_style": "italic_bold_left",
        },
        "citation_style": "bracket_numbered",
    },
    "apa": {
        "style": "APA",
        "font": "Times New Roman",
        "body_size_pt": 12,
        "abstract_size_pt": 12,
        "columns": 1,
        "column_gap_inches": 0.0,
        "margin_inches": 1.0,
        "page_size": "letter",
        "body_alignment": "left",
        "line_spacing": 2.0,
        "paragraph_spacing_after_twips": 0,
        "first_line_indent_inches": 0.5,
        "reference_hanging_indent_inches": 0.5,
        "section_rules": {
            "numbering": "none",
            "heading_style": "bold_centered",
            "subsection_numbering": "none",
            "subsection_style": "bold_left",
        },
        "citation_style": "author_year",
    },
    "acm": {
        "style": "ACM",
        "font": "Libertine",
        "body_size_pt": 9,
        "abstract_size_pt": 9,
        "columns": 2,
        "column_gap_inches": 0.25,
        "margin_inches": 0.75,
        "page_size": "letter",
        "body_alignment": "left",
        "line_spacing": 1.0,
        "paragraph_spacing_after_twips": 80,
        "first_line_indent_inches": 0.0,
        "reference_hanging_indent_inches": 0.25,
        "section_rules": {
            "numbering": "arabic",
            "heading_style": "bold_left",
            "subsection_numbering": "arabic",
            "subsection_style": "bold_left",
        },
        "citation_style": "bracket_numbered",
    },
    "nature": {
        "style": "Nature",
        "font": "Arial",
        "body_size_pt": 10,
        "abstract_size_pt": 10,
        "columns": 2,
        "column_gap_inches": 0.24,
        "margin_inches": 0.7,
        "page_size": "a4",
        "body_alignment": "left",
        "line_spacing": 1.0,
        "paragraph_spacing_after_twips": 80,
        "first_line_indent_inches": 0.0,
        "reference_hanging_indent_inches": 0.25,
        "section_rules": {
            "numbering": "none",
            "heading_style": "bold_left",
            "subsection_numbering": "none",
            "subsection_style": "bold_left",
        },
        "citation_style": "superscript",
    },
    "elsevier": {
        "style": "Elsevier",
        "font": "Times New Roman",
        "body_size_pt": 10,
        "abstract_size_pt": 10,
        "columns": 1,
        "column_gap_inches": 0.0,
        "margin_inches": 1.0,
        "page_size": "letter",
        "body_alignment": "left",
        "line_spacing": 1.15,
        "paragraph_spacing_after_twips": 120,
        "first_line_indent_inches": 0.0,
        "reference_hanging_indent_inches": 0.5,
        "section_rules": {
            "numbering": "arabic",
            "heading_style": "bold_left",
            "subsection_numbering": "arabic",
            "subsection_style": "bold_left",
        },
        "citation_style": "author_year",
    },
    "chicago": {
        "style": "Chicago",
        "font": "Times New Roman",
        "body_size_pt": 12,
        "abstract_size_pt": 12,
        "columns": 1,
        "column_gap_inches": 0.0,
        "margin_inches": 1.0,
        "page_size": "letter",
        "body_alignment": "left",
        "line_spacing": 2.0,
        "paragraph_spacing_after_twips": 0,
        "first_line_indent_inches": 0.5,
        "reference_hanging_indent_inches": 0.5,
        "section_rules": {
            "numbering": "none",
            "heading_style": "bold_centered",
            "subsection_numbering": "none",
            "subsection_style": "bold_left",
        },
        "citation_style": "superscript",
    },
}
